name: Python application test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsystemd-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Add src to PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_ENV"  # Debug output to verify PYTHONPATH

    - name: List directory structure
      run: ls -alhR  # Lists all files and directories recursively for debugging

    - name: Run pytest
      run: python -m pytest tests/

    - name: Print successful test execution
      run: echo "The tests ran successfully!"
